# .streamlit/secrets.toml
[stripe]
publishable_key = "pk_test_51RY5SLQZSkGxrGrfL3ePtfvtIMP7idCILXoaOifyjZlFDQOL34Eha5VTHMSkMAtehHMFAQKaIYQPPAcXC9fDEsqm00pxUFe3b"
api_key = "sk_test_51RY5SLQZSkGxrGrf3Bh3UJteGkG1w9GCt3VhVVX1morWCUZHCYCaMpdysTG2Ii1lugSEBABPnuj3kboFV80AhN2l00q80jh2jQ"
product_id = "prod_ST1etk9DXNvuvw"