name: Generate UN-EX Comparison Graph

on:
  workflow_dispatch: # Allows manual triggering from GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest # You can choose other runners like windows-latest or macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Checks out your repository code

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Or your preferred Python version (e.g., '3.10', '3.11')

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib # Install the plotting library

    - name: Run graph generation script
      # ULTIMATE FIX: Explicitly change directory to the repository root
      # before running the script. This bypasses any unexpected nesting.
      run: |
        cd ${{ github.workspace }}
        python generate_comparison_graph.py

    - name: Upload generated graph
      uses: actions/upload-artifact@v4 # Uploads the generated image as a workflow artifact
      with:
        name: unex-comparison-graph
        path: unex_performance_comparison.png # The name of the file your script saves
